import Header from "./(components)/header"
import "./globals.css"

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-50 text-neutral-800 px-6 md:px-12">
        <Header />
        {children}
      </body>
    </html>
  )
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}
